-- V1__Complete_Schema.sql
-- Complete database schema aligned with entity classes

-- Core Tables
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(120) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

-- Reference Tables
CREATE TABLE car_conditions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    display_name_en VARCHAR(50) NOT NULL,
    display_name_ar VARCHAR(50) NOT NULL
);

CREATE TABLE body_styles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    display_name_en VARCHAR(50) NOT NULL,
    display_name_ar VARCHAR(50) NOT NULL
);

CREATE TABLE transmissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    display_name_en VARCHAR(50) NOT NULL,
    display_name_ar VARCHAR(50) NOT NULL
);

CREATE TABLE fuel_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    display_name_en VARCHAR(50) NOT NULL,
    display_name_ar VARCHAR(50) NOT NULL
);

CREATE TABLE drive_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    display_name_en VARCHAR(50) NOT NULL,
    display_name_ar VARCHAR(50) NOT NULL
);

-- Location Tables
CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name_en VARCHAR(100) NOT NULL,
    display_name_ar VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    country_code VARCHAR(2) NOT NULL,
    region VARCHAR(100),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Car Brand and Models
CREATE TABLE car_brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    display_name_en VARCHAR(100) NOT NULL,
    display_name_ar VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE car_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    display_name_en VARCHAR(100) NOT NULL,
    display_name_ar VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (brand_id) REFERENCES car_brands(id) ON DELETE CASCADE
);

CREATE TABLE car_trims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_id BIGINT NOT NULL,
    name VARCHAR(50) NOT NULL,
    display_name_en VARCHAR(100) NOT NULL,
    display_name_ar VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (model_id) REFERENCES car_models(id) ON DELETE CASCADE
);

-- Car Listings and Media
CREATE TABLE car_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    mileage INT NOT NULL,
    model_year INT NOT NULL,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    trim VARCHAR(50),
    vin VARCHAR(17),
    stock_number VARCHAR(50),
    exterior_color VARCHAR(50),
    interior_color VARCHAR(50),
    doors INT,
    cylinders INT,
    seller_id BIGINT NOT NULL,
    location_id BIGINT,
    condition_id BIGINT,
    body_style_id BIGINT,
    transmission_id BIGINT,
    fuel_type_id BIGINT,
    drive_type_id BIGINT,
    approved BOOLEAN DEFAULT FALSE,
    sold BOOLEAN DEFAULT FALSE,
    archived BOOLEAN DEFAULT FALSE,
    expired BOOLEAN DEFAULT FALSE,
    is_user_active BOOLEAN DEFAULT TRUE,
    expiration_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE SET NULL,
    FOREIGN KEY (condition_id) REFERENCES car_conditions(id) ON DELETE SET NULL,
    FOREIGN KEY (body_style_id) REFERENCES body_styles(id) ON DELETE SET NULL,
    FOREIGN KEY (transmission_id) REFERENCES transmissions(id) ON DELETE SET NULL,
    FOREIGN KEY (fuel_type_id) REFERENCES fuel_types(id) ON DELETE SET NULL,
    FOREIGN KEY (drive_type_id) REFERENCES drive_types(id) ON DELETE SET NULL
);

CREATE TABLE listing_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL,
    file_key VARCHAR(255) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size BIGINT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    is_primary BOOLEAN DEFAULT FALSE,
    media_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (listing_id) REFERENCES car_listings(id) ON DELETE CASCADE,
    CONSTRAINT ck_listing_media_type CHECK (media_type IN ('image', 'video'))
);

-- User Features
CREATE TABLE favorites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    car_listing_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_favorites_user_car UNIQUE (user_id, car_listing_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (car_listing_id) REFERENCES car_listings(id) ON DELETE CASCADE
);

-- Indexes
CREATE INDEX idx_car_listings_brand_model_year ON car_listings(brand, model, model_year);
CREATE INDEX idx_car_listings_location ON car_listings(location_id);
CREATE INDEX idx_car_listings_seller ON car_listings(seller_id);
CREATE INDEX idx_car_models_brand_id ON car_models(brand_id);

-- Initial Roles
INSERT INTO roles (name) VALUES
('ROLE_USER'),
('ROLE_ADMIN'),
('ROLE_MODERATOR');

-- Initial Reference Data
INSERT INTO car_conditions (name, display_name_en, display_name_ar) VALUES
('excellent', 'Excellent', 'ممتاز'),
('very_good', 'Very Good', 'جيد جداً'),
('good', 'Good', 'جيد'),
('fair', 'Fair', 'مقبول');

INSERT INTO body_styles (name, display_name_en, display_name_ar) VALUES
('sedan', 'Sedan', 'سيدان'),
('suv', 'SUV', 'دفع رباعي'),
('coupe', 'Coupe', 'كوبيه'),
('hatchback', 'Hatchback', 'هاتشباك'),
('wagon', 'Wagon', 'ستيشن'),
('pickup', 'Pickup', 'بيك آب'),
('van', 'Van', 'فان'),
('convertible', 'Convertible', 'مكشوف');

INSERT INTO transmissions (name, display_name_en, display_name_ar) VALUES
('automatic', 'Automatic', 'أوتوماتيك'),
('manual', 'Manual', 'يدوي'),
('cvt', 'CVT', 'متغير مستمر'),
('dct', 'Dual Clutch', 'ثنائي القابض');

INSERT INTO fuel_types (name, display_name_en, display_name_ar) VALUES
('gasoline', 'Gasoline', 'بنزين'),
('diesel', 'Diesel', 'ديزل'),
('hybrid', 'Hybrid', 'هجين'),
('electric', 'Electric', 'كهربائي');

INSERT INTO drive_types (name, display_name_en, display_name_ar) VALUES
('fwd', 'Front Wheel Drive', 'دفع أمامي'),
('rwd', 'Rear Wheel Drive', 'دفع خلفي'),
('awd', 'All Wheel Drive', 'دفع رباعي دائم'),
('4wd', '4 Wheel Drive', 'دفع رباعي');
