version: '3.8'

services:
  vault:
    image: vault:1.13
    container_name: caryo-vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=caryo-dev-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data
    command: server -dev
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Include existing services from docker-compose.dev.yml
  # This is just the Vault service that needs to be added to your existing setup
