version: '3.9'

# This is a simplified Docker Compose file for testing the GitHub Actions workflows locally
# It includes only the minimum services needed to test the workflows

services:
  # Mock database service
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: autotrader
      POSTGRES_PASSWORD: autotrader
      POSTGRES_DB: autotrader
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U autotrader"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Mock MinIO service for S3-compatible storage
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

  # Create buckets automatically
  createbuckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/autotrader;
      /usr/bin/mc policy set public myminio/autotrader;
      exit 0;
      "

  # Mock Redis service
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
