name: Backend Integration Tests

on:
  workflow_dispatch:  # Manual trigger only
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at midnight
  pull_request:
    paths:
      - 'backend/autotrader-backend/**'
      - '.github/workflows/integration-tests.yml'
    branches: [ 'main', 'develop' ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20  # Prevent hanging builds

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for better change detection
        lfs: true
        
    # Use the Gradle setup composite action
    - name: Setup Gradle Environment
      uses: ./.github/actions/gradle-setup
      with:
        working-directory: "./backend/autotrader-backend"
        java-version: "17"
        cache: true
        
    # Use the Docker services setup composite action
    - name: Setup Docker Services
      uses: ./.github/actions/docker-services-setup
      with:
        docker-compose-file: "./backend/autotrader-backend/docker-compose.dev.yml"
        services: "db minio createbuckets redis"
        wait-time: '60'
        db-container-name: "autotrader-backend-db-1"  # Corrected container name
        db-user: "autotrader"

    # Run the actual integration tests
    - name: Run Integration Tests
      working-directory: ./backend/autotrader-backend
      run: |
        # Check available tasks
        echo "Checking available Gradle tasks..."
        ./gradlew tasks

        # Check if integrationTest task exists
        if ./gradlew tasks --all | grep -q "integrationTest"; then
          echo "integrationTest task found, running integration tests"
          ./gradlew integrationTest --info
        else
          echo "WARNING: integrationTest task not found! Running regular tests instead."
          ./gradlew test --info
        fi

        # Check if JaCoCo report tasks exist and run them
        if ./gradlew tasks --all | grep -q "jacocoTestReport"; then
          echo "jacocoTestReport task found, generating reports"
          ./gradlew jacocoTestReport --info
        fi

        if ./gradlew tasks --all | grep -q "jacocoIntegrationTestReport"; then
          echo "jacocoIntegrationTestReport task found, generating reports"
          ./gradlew jacocoIntegrationTestReport --info
        fi

    - name: Verify JaCoCo report exists
      run: |
        echo "Checking for JaCoCo report file..."
        ls -la ./backend/autotrader-backend/build/reports/jacoco/test/ || echo "JaCoCo test directory not found"
        find ./backend/autotrader-backend/build/reports/ -name "*.xml" -type f

    - name: Upload integration test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-results
        path: |
          backend/autotrader-backend/build/reports/tests/integrationTest/
          backend/autotrader-backend/build/test-results/integrationTest/

    - name: Upload test coverage
      if: success() || failure()
      uses: codecov/codecov-action@v4
      with:
        files: |
          ./backend/autotrader-backend/build/reports/jacoco/test/jacocoTestReport.xml
          ./backend/autotrader-backend/build/reports/jacoco/integrationTest/jacocoIntegrationTestReport.xml
        directory: ./backend/autotrader-backend/build/reports/
        flags: integration-tests
        fail_ci_if_error: false
        verbose: true
