name: Backend Unit Tests

on:
  workflow_dispatch:  # Manual trigger
  pull_request:
    paths:
      - 'backend/autotrader-backend/**'
      - '.github/workflows/unit-tests.yml'
      - '.github/actions/gradle-setup/**'
    branches: [ 'main', 'develop' ]  # Run on PRs to both main and develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    # Use the Gradle setup composite action
    - name: Setup Gradle Environment
      uses: ./.github/actions/gradle-setup
      with:
        working-directory: "./backend/autotrader-backend"
        java-version: "17"
        cache: true

    # Run unit tests using Gradle
    - name: Run Unit Tests
      working-directory: ./backend/autotrader-backend
      run: |
        echo "Running unit tests (excluding integration tests)..."
        
        # List all test tasks for debugging
        echo "Available test tasks:"
        ./gradlew tasks --all | grep -E "test|Test" || true
        
        # Only run unit tests, exclude integration tests by pattern
        echo "Excluding integration tests and using H2 database for unit tests only."
        ./gradlew test --tests "*UnitTest" --tests "*Test" --exclude-task integrationTest

        # Optionally, you can further filter by test class/package if needed

        # Ensure H2 is used (override profile if needed)
        export SPRING_PROFILES_ACTIVE=unit,h2

        # Generate JaCoCo reports if available
        if ./gradlew tasks --all | grep -q "jacocoTestReport"; then
          echo "Generating JaCoCo test report..."
          ./gradlew jacocoTestReport
        fi

    # Upload test results and coverage
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: |
          backend/autotrader-backend/build/reports/tests/test/
          backend/autotrader-backend/build/test-results/test/

    - name: Upload test coverage
      if: success() || failure()
      uses: codecov/codecov-action@v4
      with:
        files: ./backend/autotrader-backend/build/reports/jacoco/test/jacocoTestReport.xml
        directory: ./backend/autotrader-backend/build/reports/
        flags: unit-tests
        fail_ci_if_error: false
        verbose: true
